spring:
  datasource:
    generate-unique-name: false
    name: tacocloud
    username: sa
#    url: jdbc:h2:mem:tacocloud;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    url: jdbc:h2:tcp://localhost:9092/mem:tacocloud;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
logging:
  level:
    org.springframework: INFO